version: 2

models:
  - name: fct_covid
    columns:
      - name: record_hash
        tests:
          - unique
          - not_null
      - name: confirmed
        tests:
          - not_null
      - name: deaths
        tests:
          - not_null
      - name: file_date
        tests:
          - not_null